---
apiVersion: appmesh.k8s.aws/v1alpha1
kind: VirtualNode
metadata:
  name: ingress
  namespace: test
spec:
  meshName: global.appmesh-system
  listeners:
    - portMapping:
        port: 80
        protocol: http
  serviceDiscovery:
    dns:
      hostName: ingress.test
  backends:
    - virtualService:
        virtualServiceName: frontend.test

